
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class War3ErrorsConfig : Luban.BeanBase
    {
        public War3ErrorsConfig(ByteBuf _buf) 
        {
            Emptycontrolgroup = _buf.ReadString();
            Invalidcontrolgroup = _buf.ReadString();
            Nonunitincontrolgroup = _buf.ReadString();
            Nofood = _buf.ReadString();
            Maxsupply = _buf.ReadString();
            Nogold = _buf.ReadString();
            Nolumber = _buf.ReadString();
            Nomana = _buf.ReadString();
            Cooldown = _buf.ReadString();
            Noroom = _buf.ReadString();
            Canttransport = _buf.ReadString();
            Cantdevour = _buf.ReadString();
            Cantcyclone = _buf.ReadString();
            Cantspiritwolf = _buf.ReadString();
            Cantpossess = _buf.ReadString();
            Cantmanaburn = _buf.ReadString();
            Onlyattackers = _buf.ReadString();
            Notentangledmine = _buf.ReadString();
            Notblightedmine = _buf.ReadString();
            Alreadyentangled = _buf.ReadString();
            Alreadyblightedmine = _buf.ReadString();
            Targetwispresources = _buf.ReadString();
            Targetblightedmine = _buf.ReadString();
            Entangleminefirst = _buf.ReadString();
            Blightminefirst = _buf.ReadString();
            Entangledminefull = _buf.ReadString();
            Blightringfull = _buf.ReadString();
            Acolytealreadymining = _buf.ReadString();
            Nototherplayersmine = _buf.ReadString();
            Targgetmine = _buf.ReadString();
            Targgetresources = _buf.ReadString();
            Humanbuilding = _buf.ReadString();
            Undeadbuilding = _buf.ReadString();
            Underconstruction = _buf.ReadString();
            Alreadyrebuilding = _buf.ReadString();
            Creeptoopowerful = _buf.ReadString();
            Hibernating = _buf.ReadString();
            Magicleashed = _buf.ReadString();
            Immunetomagic = _buf.ReadString();
            Holybolttarget = _buf.ReadString();
            Deathcoiltarget = _buf.ReadString();
            Dispelmagictarget = _buf.ReadString();
            Treeoccupied = _buf.ReadString();
            Coupletarget = _buf.ReadString();
            Mounthippogryphtarget = _buf.ReadString();
            Archerridertarget = _buf.ReadString();
            Cantsee = _buf.ReadString();
            Cantplace = _buf.ReadString();
            Outofbounds = _buf.ReadString();
            Offblight = _buf.ReadString();
            Tooclosetomine = _buf.ReadString();
            Tooclosetohall = _buf.ReadString();
            Notonshoreline = _buf.ReadString();
            Buildingblocked = _buf.ReadString();
            Teleportfail = _buf.ReadString();
            Stumpblocked = _buf.ReadString();
            Cantland = _buf.ReadString();
            Cantroot = _buf.ReadString();
            Cantrootunit = _buf.ReadString();
            Mustroottoentangle = _buf.ReadString();
            Mustbeclosertomine = _buf.ReadString();
            Minenotentangleable = _buf.ReadString();
            Notinrange = _buf.ReadString();
            UnderRange = _buf.ReadString();
            Notthisunit = _buf.ReadString();
            Targetunit = _buf.ReadString();
            Targetstructuretree = _buf.ReadString();
            Targetground = _buf.ReadString();
            Targetair = _buf.ReadString();
            Targetstructure = _buf.ReadString();
            Targetward = _buf.ReadString();
            Targetitem = _buf.ReadString();
            Targettree = _buf.ReadString();
            Targetrepair = _buf.ReadString();
            Targetbridge = _buf.ReadString();
            Targetnaval = _buf.ReadString();
            Targetowned = _buf.ReadString();
            Targetally = _buf.ReadString();
            Targetneutral = _buf.ReadString();
            Targetenemy = _buf.ReadString();
            Targetcontrol = _buf.ReadString();
            Targethero = _buf.ReadString();
            Targetenemyhero = _buf.ReadString();
            Targetcorpse = _buf.ReadString();
            Targetfleshycorpse = _buf.ReadString();
            Targetbonecorpse = _buf.ReadString();
            Targetundead = _buf.ReadString();
            Targetmechanical = _buf.ReadString();
            Targetmoveable = _buf.ReadString();
            Targetorganicground = _buf.ReadString();
            Targetancient = _buf.ReadString();
            Targetarmoredtransport = _buf.ReadString();
            Targetmanauser = _buf.ReadString();
            Targetbunkerunit = _buf.ReadString();
            Targetwisp = _buf.ReadString();
            Targetacolyte = _buf.ReadString();
            Targetpit = _buf.ReadString();
            Needemptytree = _buf.ReadString();
            Needowltree = _buf.ReadString();
            Cantfindcorpse = _buf.ReadString();
            Cantfindfriendlycorpse = _buf.ReadString();
            Nounits = _buf.ReadString();
            Noground = _buf.ReadString();
            Noair = _buf.ReadString();
            Nostructure = _buf.ReadString();
            Noward = _buf.ReadString();
            Noitem = _buf.ReadString();
            Nodebris = _buf.ReadString();
            Notree = _buf.ReadString();
            Nowall = _buf.ReadString();
            Nobridge = _buf.ReadString();
            Notfrozenbldg = _buf.ReadString();
            Nonaval = _buf.ReadString();
            Nottownhall = _buf.ReadString();
            Notownportalhalls = _buf.ReadString();
            Notself = _buf.ReadString();
            Notowned = _buf.ReadString();
            Notfriendly = _buf.ReadString();
            Notneutral = _buf.ReadString();
            Notenemy = _buf.ReadString();
            Notcargo = _buf.ReadString();
            Nothidden = _buf.ReadString();
            Nothiddenitem = _buf.ReadString();
            Notinvulnerable = _buf.ReadString();
            Nohero = _buf.ReadString();
            Notcorpse = _buf.ReadString();
            Notfleshycorpse = _buf.ReadString();
            Notbonecorpse = _buf.ReadString();
            Notmechanical = _buf.ReadString();
            Notorganic = _buf.ReadString();
            Notdisabled = _buf.ReadString();
            Cantattackloc = _buf.ReadString();
            Canttargetloc = _buf.ReadString();
            Inventoryfull = _buf.ReadString();
            Inventoryinteract = _buf.ReadString();
            NeedInventory = _buf.ReadString();
            Needretrainablehero = _buf.ReadString();
            Neednearbyhero = _buf.ReadString();
            Neednearbypatron = _buf.ReadString();
            Notsapper = _buf.ReadString();
            Notancient = _buf.ReadString();
            Notsummoned = _buf.ReadString();
            Nottransport = _buf.ReadString();
            Notunsummoned = _buf.ReadString();
            Notillusion = _buf.ReadString();
            Notmorphing = _buf.ReadString();
            Notdot = _buf.ReadString();
            Illusionscantharvest = _buf.ReadString();
            Illusionscantpickup = _buf.ReadString();
            Cantpolymorphunit = _buf.ReadString();
            Notundead = _buf.ReadString();
            Heromaxed = _buf.ReadString();
            HPmaxed = _buf.ReadString();
            Manamaxed = _buf.ReadString();
            HPmanamaxed = _buf.ReadString();
            UnitHPmaxed = _buf.ReadString();
            UnitManaMaxed = _buf.ReadString();
            RepairHPmaxed = _buf.ReadString();
            Alreadybeinghealed = _buf.ReadString();
            Alreadybeingrepaired = _buf.ReadString();
            Pitalreadysacrificing = _buf.ReadString();
            Outofstock = _buf.ReadString();
            Cooldownstock = _buf.ReadString();
            Cantdrop = _buf.ReadString();
            Cantpawn = _buf.ReadString();
            Calltoarms = _buf.ReadString();
            Calltoarmspeasant = _buf.ReadString();
            Backtowork = _buf.ReadString();
            Backtoworkmilitia = _buf.ReadString();
            BattleStations = _buf.ReadString();
            Replaceme = _buf.ReadString();
            Notliquidfirebldg = _buf.ReadString();
            Notethereal = _buf.ReadString();
            Needstealbuff = _buf.ReadString();
            Needmeleeattacker = _buf.ReadString();
            Needrangedattacker = _buf.ReadString();
            Needspecialattacker = _buf.ReadString();
            Needattacker = _buf.ReadString();
            Needcaster = _buf.ReadString();
            Needattackerorcaster = _buf.ReadString();
            Nopreservationtarget = _buf.ReadString();
            Canttransformitem = _buf.ReadString();
            Notmocunit = _buf.ReadString();
            Cantimpale = _buf.ReadString();
            Needpositivebuff = _buf.ReadString();
            Needposbufforsummoned = _buf.ReadString();
            Neednegativebuff = _buf.ReadString();
            Absorbmana = _buf.ReadString();
            Canttakeitem = _buf.ReadString();
            Cantdropitem = _buf.ReadString();
            Cantuseitem = _buf.ReadString();
            Notpowerup = _buf.ReadString();
            Itemcooldown = _buf.ReadString();
            Cantfindcoupletarget = _buf.ReadString();
            Notdisabledinventory = _buf.ReadString();
            Resistantskin = _buf.ReadString();
            Notinvulnerablespell = _buf.ReadString();
            Needsummoned = _buf.ReadString();
            Cantsubmergethere = _buf.ReadString();
            Alreadydoomed = _buf.ReadString();

            EndInit();
        }

        public static War3ErrorsConfig DeserializeWar3ErrorsConfig(ByteBuf _buf)
        {
            return new War3ErrorsConfig(_buf);
        }

        /// <summary>
        /// 不能组成空的控制编组。
        /// </summary>
        public readonly string Emptycontrolgroup;
        /// <summary>
        /// 不能将非自己控制的单位编入控制编组中。
        /// </summary>
        public readonly string Invalidcontrolgroup;
        /// <summary>
        /// 编组只能由单位组成。
        /// </summary>
        public readonly string Nonunitincontrolgroup;
        /// <summary>
        /// 建造更多的农场来继续生产单位。;建造更多的地洞来继续生产单位。;召唤更多的通灵塔来继续生产单位。;建造更多的月亮井来继续生产单位。
        /// </summary>
        public readonly string Nofood;
        /// <summary>
        /// 达到食物上限，无法继续生产单位。
        /// </summary>
        public readonly string Maxsupply;
        /// <summary>
        /// 黄金不足。
        /// </summary>
        public readonly string Nogold;
        /// <summary>
        /// 木材不足。
        /// </summary>
        public readonly string Nolumber;
        /// <summary>
        /// 法力值不足。
        /// </summary>
        public readonly string Nomana;
        /// <summary>
        /// 法术尚未就绪。
        /// </summary>
        public readonly string Cooldown;
        /// <summary>
        /// 运载空间不足。
        /// </summary>
        public readonly string Noroom;
        /// <summary>
        /// 不能装载目标。
        /// </summary>
        public readonly string Canttransport;
        /// <summary>
        /// 不能吞噬该单位。
        /// </summary>
        public readonly string Cantdevour;
        /// <summary>
        /// 不能对该单位施放飓风术。
        /// </summary>
        public readonly string Cantcyclone;
        /// <summary>
        /// 不能对该目标施放野性之魂。
        /// </summary>
        public readonly string Cantspiritwolf;
        /// <summary>
        /// 不能对该目标施放占据。
        /// </summary>
        public readonly string Cantpossess;
        /// <summary>
        /// 不能对该目标施放法力燃烧。
        /// </summary>
        public readonly string Cantmanaburn;
        /// <summary>
        /// 必须以战斗单位为目标。
        /// </summary>
        public readonly string Onlyattackers;
        /// <summary>
        /// 不能使用被缠绕的金矿。
        /// </summary>
        public readonly string Notentangledmine;
        /// <summary>
        /// 不能使用闹鬼金矿。
        /// </summary>
        public readonly string Notblightedmine;
        /// <summary>
        /// 该金矿已被缠绕。
        /// </summary>
        public readonly string Alreadyentangled;
        /// <summary>
        /// 该金矿已变成闹鬼金矿。
        /// </summary>
        public readonly string Alreadyblightedmine;
        /// <summary>
        /// 必须以树木或被缠绕的金矿为目标。
        /// </summary>
        public readonly string Targetwispresources;
        /// <summary>
        /// 必须以闹鬼金矿为目标。
        /// </summary>
        public readonly string Targetblightedmine;
        /// <summary>
        /// 必须先将金矿缠绕。
        /// </summary>
        public readonly string Entangleminefirst;
        /// <summary>
        /// 必须先让金矿变成闹鬼金矿。
        /// </summary>
        public readonly string Blightminefirst;
        /// <summary>
        /// 那个金矿不需要更多的小精灵。
        /// </summary>
        public readonly string Entangledminefull;
        /// <summary>
        /// 那个金矿不需要更多的侍僧。
        /// </summary>
        public readonly string Blightringfull;
        /// <summary>
        /// 选中的侍僧已经在采矿了。
        /// </summary>
        public readonly string Acolytealreadymining;
        /// <summary>
        /// 不能使用被其他玩家控制的金矿。
        /// </summary>
        public readonly string Nototherplayersmine;
        /// <summary>
        /// 必须以金矿为目标。
        /// </summary>
        public readonly string Targgetmine;
        /// <summary>
        /// 必须以资源为目标。
        /// </summary>
        public readonly string Targgetresources;
        /// <summary>
        /// 必须以人类建筑为目标。
        /// </summary>
        public readonly string Humanbuilding;
        /// <summary>
        /// 必须以亡灵建筑为目标。
        /// </summary>
        public readonly string Undeadbuilding;
        /// <summary>
        /// 该建筑正在建造中。
        /// </summary>
        public readonly string Underconstruction;
        /// <summary>
        /// 该建筑已在建造中。
        /// </summary>
        public readonly string Alreadyrebuilding;
        /// <summary>
        /// 这个生物太过强大。
        /// </summary>
        public readonly string Creeptoopowerful;
        /// <summary>
        /// 该单位已处于休眠状态。
        /// </summary>
        public readonly string Hibernating;
        /// <summary>
        /// 该单位已被束缚。
        /// </summary>
        public readonly string Magicleashed;
        /// <summary>
        /// 该单位对魔法免疫。
        /// </summary>
        public readonly string Immunetomagic;
        /// <summary>
        /// 必须以友方生命单位或敌方亡灵单位为目标。
        /// </summary>
        public readonly string Holybolttarget;
        /// <summary>
        /// 必须以敌方生命单位或友方亡灵单位为目标。
        /// </summary>
        public readonly string Deathcoiltarget;
        /// <summary>
        /// 必须以一个单位或者一片荒芜为目标。
        /// </summary>
        public readonly string Dispelmagictarget;
        /// <summary>
        /// 这颗树已被占用，请选择其他树木。
        /// </summary>
        public readonly string Treeoccupied;
        /// <summary>
        /// 不能与该单位融合。
        /// </summary>
        public readonly string Coupletarget;
        /// <summary>
        /// 必须以角鹰兽为目标。
        /// </summary>
        public readonly string Mounthippogryphtarget;
        /// <summary>
        /// 必须以弓箭手为目标。
        /// </summary>
        public readonly string Archerridertarget;
        /// <summary>
        /// 必须先探索那里。
        /// </summary>
        public readonly string Cantsee;
        /// <summary>
        /// 不能在那里建造。
        /// </summary>
        public readonly string Cantplace;
        /// <summary>
        /// 目标位置已超出地图边界。
        /// </summary>
        public readonly string Outofbounds;
        /// <summary>
        /// 必须在荒芜之上召唤建筑。
        /// </summary>
        public readonly string Offblight;
        /// <summary>
        /// 不能在离金矿太近的地方建造。
        /// </summary>
        public readonly string Tooclosetomine;
        /// <summary>
        /// 不能在离城镇大厅太近的地方创建金矿。
        /// </summary>
        public readonly string Tooclosetohall;
        /// <summary>
        /// 不能在远离海岸线的地方建造。
        /// </summary>
        public readonly string Notonshoreline;
        /// <summary>
        /// 没有空间可以放置新生产出的单位。
        /// </summary>
        public readonly string Buildingblocked;
        /// <summary>
        /// 该单位不能被传送。
        /// </summary>
        public readonly string Teleportfail;
        /// <summary>
        /// 有东西封住了那根树桩。
        /// </summary>
        public readonly string Stumpblocked;
        /// <summary>
        /// 不能在那里着陆。
        /// </summary>
        public readonly string Cantland;
        /// <summary>
        /// 不能在那里扎根。
        /// </summary>
        public readonly string Cantroot;
        /// <summary>
        /// 目标不能再扎根了。
        /// </summary>
        public readonly string Cantrootunit;
        /// <summary>
        /// 必须在金矿附近扎根以进行缠绕。
        /// </summary>
        public readonly string Mustroottoentangle;
        /// <summary>
        /// 必须在金矿附近扎根。
        /// </summary>
        public readonly string Mustbeclosertomine;
        /// <summary>
        /// 该金矿不能被缠绕。
        /// </summary>
        public readonly string Minenotentangleable;
        /// <summary>
        /// 目标超出射程。
        /// </summary>
        public readonly string Notinrange;
        /// <summary>
        /// 目标距离低于最小射程。
        /// </summary>
        public readonly string UnderRange;
        /// <summary>
        /// 不能以该单位为目标。
        /// </summary>
        public readonly string Notthisunit;
        /// <summary>
        /// 该动作必须以单位为目标。
        /// </summary>
        public readonly string Targetunit;
        /// <summary>
        /// 必须以建筑或树木为目标。
        /// </summary>
        public readonly string Targetstructuretree;
        /// <summary>
        /// 必须以地面单位为目标。
        /// </summary>
        public readonly string Targetground;
        /// <summary>
        /// 必须以空中单位为目标。
        /// </summary>
        public readonly string Targetair;
        /// <summary>
        /// 必须以建筑为目标。
        /// </summary>
        public readonly string Targetstructure;
        /// <summary>
        /// 必须以结界为目标。
        /// </summary>
        public readonly string Targetward;
        /// <summary>
        /// 必须以物品为目标。
        /// </summary>
        public readonly string Targetitem;
        /// <summary>
        /// 必须以树木为目标。
        /// </summary>
        public readonly string Targettree;
        /// <summary>
        /// 必须以建筑和机械单位为目标。
        /// </summary>
        public readonly string Targetrepair;
        /// <summary>
        /// 必须以桥梁为目标。
        /// </summary>
        public readonly string Targetbridge;
        /// <summary>
        /// 必须以海上单位为目标。
        /// </summary>
        public readonly string Targetnaval;
        /// <summary>
        /// 必须以你自己的单位为目标。
        /// </summary>
        public readonly string Targetowned;
        /// <summary>
        /// 必须以友方单位为目标。
        /// </summary>
        public readonly string Targetally;
        /// <summary>
        /// 必须以中立单位为目标。
        /// </summary>
        public readonly string Targetneutral;
        /// <summary>
        /// 必须以敌方单位为目标。
        /// </summary>
        public readonly string Targetenemy;
        /// <summary>
        /// 必须以你能控制的单位为目标。
        /// </summary>
        public readonly string Targetcontrol;
        /// <summary>
        /// 必须以英雄为目标。
        /// </summary>
        public readonly string Targethero;
        /// <summary>
        /// 必须以敌方英雄为目标。
        /// </summary>
        public readonly string Targetenemyhero;
        /// <summary>
        /// 必须以尸体为目标。
        /// </summary>
        public readonly string Targetcorpse;
        /// <summary>
        /// 必须以血肉尸体为目标。
        /// </summary>
        public readonly string Targetfleshycorpse;
        /// <summary>
        /// 必须以骨骼尸体为目标。
        /// </summary>
        public readonly string Targetbonecorpse;
        /// <summary>
        /// 必须以亡灵单位为目标。
        /// </summary>
        public readonly string Targetundead;
        /// <summary>
        /// 必须以机械单位为目标。
        /// </summary>
        public readonly string Targetmechanical;
        /// <summary>
        /// 必须以可移动单位为目标。
        /// </summary>
        public readonly string Targetmoveable;
        /// <summary>
        /// 必须以有机地面单位为目标。
        /// </summary>
        public readonly string Targetorganicground;
        /// <summary>
        /// 必须以古树为目标。
        /// </summary>
        public readonly string Targetancient;
        /// <summary>
        /// 必须以装甲载具为目标。
        /// </summary>
        public readonly string Targetarmoredtransport;
        /// <summary>
        /// 必须以拥有法力值的单位为目标。
        /// </summary>
        public readonly string Targetmanauser;
        /// <summary>
        /// 必须以苦工为目标。
        /// </summary>
        public readonly string Targetbunkerunit;
        /// <summary>
        /// 必须以小精灵为目标。
        /// </summary>
        public readonly string Targetwisp;
        /// <summary>
        /// 必须以侍僧为目标。
        /// </summary>
        public readonly string Targetacolyte;
        /// <summary>
        /// 必须以献祭深渊为目标。
        /// </summary>
        public readonly string Targetpit;
        /// <summary>
        /// 这颗树已经被一只猫头鹰占据。
        /// </summary>
        public readonly string Needemptytree;
        /// <summary>
        /// 这颗树尚未被猫头鹰占据。
        /// </summary>
        public readonly string Needowltree;
        /// <summary>
        /// 附近没有可使用的尸体。
        /// </summary>
        public readonly string Cantfindcorpse;
        /// <summary>
        /// 附近没有友方单位的尸体。
        /// </summary>
        public readonly string Cantfindfriendlycorpse;
        /// <summary>
        /// 不能以单位为目标。
        /// </summary>
        public readonly string Nounits;
        /// <summary>
        /// 不能以地面单位为目标。
        /// </summary>
        public readonly string Noground;
        /// <summary>
        /// 不能以空中单位为目标。
        /// </summary>
        public readonly string Noair;
        /// <summary>
        /// 不能以建筑为目标。
        /// </summary>
        public readonly string Nostructure;
        /// <summary>
        /// 不能以结界为目标。
        /// </summary>
        public readonly string Noward;
        /// <summary>
        /// 不能以物品为目标。
        /// </summary>
        public readonly string Noitem;
        /// <summary>
        /// 不能以残骸为目标。
        /// </summary>
        public readonly string Nodebris;
        /// <summary>
        /// 不能以树木为目标。
        /// </summary>
        public readonly string Notree;
        /// <summary>
        /// 不能以墙壁为目标。
        /// </summary>
        public readonly string Nowall;
        /// <summary>
        /// 不能以桥梁为目标。
        /// </summary>
        public readonly string Nobridge;
        /// <summary>
        /// 目标建筑已被冰冻。
        /// </summary>
        public readonly string Notfrozenbldg;
        /// <summary>
        /// 不能以海上单位为目标。
        /// </summary>
        public readonly string Nonaval;
        /// <summary>
        /// 必须以友方城镇大厅为目标。;必须以友方大厅为目标。;必须以友方城镇大厅为目标。;必须以友方城镇大厅为目标。
        /// </summary>
        public readonly string Nottownhall;
        /// <summary>
        /// 没有友方城镇大厅可作为城镇传送的目标。;没有友方大厅可作为城镇传送的目标。;没有友方城镇大厅可作为城镇传送的目标。;没有友方城镇大厅可作为城镇传送的目标。
        /// </summary>
        public readonly string Notownportalhalls;
        /// <summary>
        /// 不能以自身为目标。
        /// </summary>
        public readonly string Notself;
        /// <summary>
        /// 不能以自己的单位为目标。
        /// </summary>
        public readonly string Notowned;
        /// <summary>
        /// 不能以友方单位为目标。
        /// </summary>
        public readonly string Notfriendly;
        /// <summary>
        /// 不能以中立单位为目标。
        /// </summary>
        public readonly string Notneutral;
        /// <summary>
        /// 不能以敌方单位为目标。
        /// </summary>
        public readonly string Notenemy;
        /// <summary>
        /// 无法以建筑或载具内的单位为目标。
        /// </summary>
        public readonly string Notcargo;
        /// <summary>
        /// 目标在地图上不可见。
        /// </summary>
        public readonly string Nothidden;
        /// <summary>
        /// 不能以携带的物品为目标。
        /// </summary>
        public readonly string Nothiddenitem;
        /// <summary>
        /// 目标是无敌的。
        /// </summary>
        public readonly string Notinvulnerable;
        /// <summary>
        /// 不能以英雄为目标。
        /// </summary>
        public readonly string Nohero;
        /// <summary>
        /// 目标必须是生命单位。
        /// </summary>
        public readonly string Notcorpse;
        /// <summary>
        /// 不能以血肉尸体为目标。
        /// </summary>
        public readonly string Notfleshycorpse;
        /// <summary>
        /// 不能以骨骼尸体为目标。
        /// </summary>
        public readonly string Notbonecorpse;
        /// <summary>
        /// 必须以有机单位为目标。
        /// </summary>
        public readonly string Notmechanical;
        /// <summary>
        /// 不能以有机单位为目标。
        /// </summary>
        public readonly string Notorganic;
        /// <summary>
        /// 施法单位移动已被禁用。
        /// </summary>
        public readonly string Notdisabled;
        /// <summary>
        /// 不能进攻那里。
        /// </summary>
        public readonly string Cantattackloc;
        /// <summary>
        /// 不能以那里为目标。
        /// </summary>
        public readonly string Canttargetloc;
        /// <summary>
        /// 物品栏已满。
        /// </summary>
        public readonly string Inventoryfull;
        /// <summary>
        /// 选择一个拥有物品栏的单位。
        /// </summary>
        public readonly string Inventoryinteract;
        /// <summary>
        /// 只有带有物品栏的单位才能捡起该物品。
        /// </summary>
        public readonly string NeedInventory;
        /// <summary>
        /// 只有技能冷却完毕的英雄才能使用该物品。
        /// </summary>
        public readonly string Needretrainablehero;
        /// <summary>
        /// 周围必须有一个英雄。
        /// </summary>
        public readonly string Neednearbyhero;
        /// <summary>
        /// 周围必须有一个有效的支持目标。
        /// </summary>
        public readonly string Neednearbypatron;
        /// <summary>
        /// 不能以工兵为目标。
        /// </summary>
        public readonly string Notsapper;
        /// <summary>
        /// 不能以古树为目标。
        /// </summary>
        public readonly string Notancient;
        /// <summary>
        /// 不能以召唤单位为目标。
        /// </summary>
        public readonly string Notsummoned;
        /// <summary>
        /// 不能以载具和掩体为目标。
        /// </summary>
        public readonly string Nottransport;
        /// <summary>
        /// 该单位正在被反召唤。
        /// </summary>
        public readonly string Notunsummoned;
        /// <summary>
        /// 不能以幻象为目标。
        /// </summary>
        public readonly string Notillusion;
        /// <summary>
        /// 不能以变形单位为目标。
        /// </summary>
        public readonly string Notmorphing;
        /// <summary>
        /// 不能以猛禽德鲁伊为目标。
        /// </summary>
        public readonly string Notdot;
        /// <summary>
        /// 幻象不能采集资源。
        /// </summary>
        public readonly string Illusionscantharvest;
        /// <summary>
        /// 幻象不能捡起物品。
        /// </summary>
        public readonly string Illusionscantpickup;
        /// <summary>
        /// 该单位对变形术免疫。
        /// </summary>
        public readonly string Cantpolymorphunit;
        /// <summary>
        /// 不能以亡灵单位为目标。
        /// </summary>
        public readonly string Notundead;
        /// <summary>
        /// 英雄已达到最高等级。
        /// </summary>
        public readonly string Heromaxed;
        /// <summary>
        /// 英雄的生命值已满。
        /// </summary>
        public readonly string HPmaxed;
        /// <summary>
        /// 法力值已满。
        /// </summary>
        public readonly string Manamaxed;
        /// <summary>
        /// 生命值和法力值已满。
        /// </summary>
        public readonly string HPmanamaxed;
        /// <summary>
        /// 生命值已满。
        /// </summary>
        public readonly string UnitHPmaxed;
        /// <summary>
        /// 法力值已满。
        /// </summary>
        public readonly string UnitManaMaxed;
        /// <summary>
        /// 目标并未受到伤害。
        /// </summary>
        public readonly string RepairHPmaxed;
        /// <summary>
        /// 目标已受到治疗。
        /// </summary>
        public readonly string Alreadybeinghealed;
        /// <summary>
        /// 目标已受到修理。
        /// </summary>
        public readonly string Alreadybeingrepaired;
        /// <summary>
        /// 献祭深渊已在献祭一名侍僧。
        /// </summary>
        public readonly string Pitalreadysacrificing;
        /// <summary>
        /// 已断货
        /// </summary>
        public readonly string Outofstock;
        /// <summary>
        /// 已断货
        /// </summary>
        public readonly string Cooldownstock;
        /// <summary>
        /// 物品必须放在物品栏中。
        /// </summary>
        public readonly string Cantdrop;
        /// <summary>
        /// 物品不能被抵押掉。
        /// </summary>
        public readonly string Cantpawn;
        /// <summary>
        /// 找不到任何农夫。
        /// </summary>
        public readonly string Calltoarms;
        /// <summary>
        /// 没有找到可以将民兵转换成农夫的城镇大厅。
        /// </summary>
        public readonly string Calltoarmspeasant;
        /// <summary>
        /// 找不到任何民兵。
        /// </summary>
        public readonly string Backtowork;
        /// <summary>
        /// 没有找到可以将民兵转换成农夫的城镇大厅。
        /// </summary>
        public readonly string Backtoworkmilitia;
        /// <summary>
        /// 找不到任何苦工。
        /// </summary>
        public readonly string BattleStations;
        /// <summary>
        /// 请用有意义的文字来替换这条错误消息！
        /// </summary>
        public readonly string Replaceme;
        /// <summary>
        /// 目标建筑已被火油瓶点燃。
        /// </summary>
        public readonly string Notliquidfirebldg;
        /// <summary>
        /// 虚灵单位只会受到法术和魔法攻击的伤害。
        /// </summary>
        public readonly string Notethereal;
        /// <summary>
        /// 目标身上没有可窃取的魔法效果。
        /// </summary>
        public readonly string Needstealbuff;
        /// <summary>
        /// 必须以近战单位为目标。
        /// </summary>
        public readonly string Needmeleeattacker;
        /// <summary>
        /// 必须以远程战斗单位为目标。
        /// </summary>
        public readonly string Needrangedattacker;
        /// <summary>
        /// 必须以特定战斗单位为目标。
        /// </summary>
        public readonly string Needspecialattacker;
        /// <summary>
        /// 必须以战斗单位为目标。
        /// </summary>
        public readonly string Needattacker;
        /// <summary>
        /// 必须以施法单位为目标。
        /// </summary>
        public readonly string Needcaster;
        /// <summary>
        /// 必须以战斗单位或施法单位为目标。
        /// </summary>
        public readonly string Needattackerorcaster;
        /// <summary>
        /// 没有可将目标传送过去的建筑。
        /// </summary>
        public readonly string Nopreservationtarget;
        /// <summary>
        /// 不能转换该物品。
        /// </summary>
        public readonly string Canttransformitem;
        /// <summary>
        /// 该单位已被火焰标记。
        /// </summary>
        public readonly string Notmocunit;
        /// <summary>
        /// 不能刺穿该单位。
        /// </summary>
        public readonly string Cantimpale;
        /// <summary>
        /// 必须以带有增益效果的敌方单位为目标。
        /// </summary>
        public readonly string Needpositivebuff;
        /// <summary>
        /// 必须以带有增益效果的敌方单位或召唤单位为目标。
        /// </summary>
        public readonly string Needposbufforsummoned;
        /// <summary>
        /// 必须以带有减益效果的友方单位为目标。
        /// </summary>
        public readonly string Neednegativebuff;
        /// <summary>
        /// 法力不足，无法吸收。
        /// </summary>
        public readonly string Absorbmana;
        /// <summary>
        /// 不能捡起该物品。
        /// </summary>
        public readonly string Canttakeitem;
        /// <summary>
        /// 不能丢掉该物品。
        /// </summary>
        public readonly string Cantdropitem;
        /// <summary>
        /// 不能使用该物品。
        /// </summary>
        public readonly string Cantuseitem;
        /// <summary>
        /// 不能使用道具。
        /// </summary>
        public readonly string Notpowerup;
        /// <summary>
        /// 该物品正在冷却。
        /// </summary>
        public readonly string Itemcooldown;
        /// <summary>
        /// 不能找到配对目标。
        /// </summary>
        public readonly string Cantfindcoupletarget;
        /// <summary>
        /// 该单位的物品栏已被禁用。
        /// </summary>
        public readonly string Notdisabledinventory;
        /// <summary>
        /// 该单位拥有抗性体肤。
        /// </summary>
        public readonly string Resistantskin;
        /// <summary>
        /// 不能使用给予无敌的法术和物品。
        /// </summary>
        public readonly string Notinvulnerablespell;
        /// <summary>
        /// 必须以召唤单位为目标。
        /// </summary>
        public readonly string Needsummoned;
        /// <summary>
        /// 不能在那里潜水。
        /// </summary>
        public readonly string Cantsubmergethere;
        /// <summary>
        /// 该单位已受到末日降临的折磨。
        /// </summary>
        public readonly string Alreadydoomed;
    
        public const int __ID__ = -1090227048;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Emptycontrolgroup:" + Emptycontrolgroup + ","
            + "Invalidcontrolgroup:" + Invalidcontrolgroup + ","
            + "Nonunitincontrolgroup:" + Nonunitincontrolgroup + ","
            + "Nofood:" + Nofood + ","
            + "Maxsupply:" + Maxsupply + ","
            + "Nogold:" + Nogold + ","
            + "Nolumber:" + Nolumber + ","
            + "Nomana:" + Nomana + ","
            + "Cooldown:" + Cooldown + ","
            + "Noroom:" + Noroom + ","
            + "Canttransport:" + Canttransport + ","
            + "Cantdevour:" + Cantdevour + ","
            + "Cantcyclone:" + Cantcyclone + ","
            + "Cantspiritwolf:" + Cantspiritwolf + ","
            + "Cantpossess:" + Cantpossess + ","
            + "Cantmanaburn:" + Cantmanaburn + ","
            + "Onlyattackers:" + Onlyattackers + ","
            + "Notentangledmine:" + Notentangledmine + ","
            + "Notblightedmine:" + Notblightedmine + ","
            + "Alreadyentangled:" + Alreadyentangled + ","
            + "Alreadyblightedmine:" + Alreadyblightedmine + ","
            + "Targetwispresources:" + Targetwispresources + ","
            + "Targetblightedmine:" + Targetblightedmine + ","
            + "Entangleminefirst:" + Entangleminefirst + ","
            + "Blightminefirst:" + Blightminefirst + ","
            + "Entangledminefull:" + Entangledminefull + ","
            + "Blightringfull:" + Blightringfull + ","
            + "Acolytealreadymining:" + Acolytealreadymining + ","
            + "Nototherplayersmine:" + Nototherplayersmine + ","
            + "Targgetmine:" + Targgetmine + ","
            + "Targgetresources:" + Targgetresources + ","
            + "Humanbuilding:" + Humanbuilding + ","
            + "Undeadbuilding:" + Undeadbuilding + ","
            + "Underconstruction:" + Underconstruction + ","
            + "Alreadyrebuilding:" + Alreadyrebuilding + ","
            + "Creeptoopowerful:" + Creeptoopowerful + ","
            + "Hibernating:" + Hibernating + ","
            + "Magicleashed:" + Magicleashed + ","
            + "Immunetomagic:" + Immunetomagic + ","
            + "Holybolttarget:" + Holybolttarget + ","
            + "Deathcoiltarget:" + Deathcoiltarget + ","
            + "Dispelmagictarget:" + Dispelmagictarget + ","
            + "Treeoccupied:" + Treeoccupied + ","
            + "Coupletarget:" + Coupletarget + ","
            + "Mounthippogryphtarget:" + Mounthippogryphtarget + ","
            + "Archerridertarget:" + Archerridertarget + ","
            + "Cantsee:" + Cantsee + ","
            + "Cantplace:" + Cantplace + ","
            + "Outofbounds:" + Outofbounds + ","
            + "Offblight:" + Offblight + ","
            + "Tooclosetomine:" + Tooclosetomine + ","
            + "Tooclosetohall:" + Tooclosetohall + ","
            + "Notonshoreline:" + Notonshoreline + ","
            + "Buildingblocked:" + Buildingblocked + ","
            + "Teleportfail:" + Teleportfail + ","
            + "Stumpblocked:" + Stumpblocked + ","
            + "Cantland:" + Cantland + ","
            + "Cantroot:" + Cantroot + ","
            + "Cantrootunit:" + Cantrootunit + ","
            + "Mustroottoentangle:" + Mustroottoentangle + ","
            + "Mustbeclosertomine:" + Mustbeclosertomine + ","
            + "Minenotentangleable:" + Minenotentangleable + ","
            + "Notinrange:" + Notinrange + ","
            + "UnderRange:" + UnderRange + ","
            + "Notthisunit:" + Notthisunit + ","
            + "Targetunit:" + Targetunit + ","
            + "Targetstructuretree:" + Targetstructuretree + ","
            + "Targetground:" + Targetground + ","
            + "Targetair:" + Targetair + ","
            + "Targetstructure:" + Targetstructure + ","
            + "Targetward:" + Targetward + ","
            + "Targetitem:" + Targetitem + ","
            + "Targettree:" + Targettree + ","
            + "Targetrepair:" + Targetrepair + ","
            + "Targetbridge:" + Targetbridge + ","
            + "Targetnaval:" + Targetnaval + ","
            + "Targetowned:" + Targetowned + ","
            + "Targetally:" + Targetally + ","
            + "Targetneutral:" + Targetneutral + ","
            + "Targetenemy:" + Targetenemy + ","
            + "Targetcontrol:" + Targetcontrol + ","
            + "Targethero:" + Targethero + ","
            + "Targetenemyhero:" + Targetenemyhero + ","
            + "Targetcorpse:" + Targetcorpse + ","
            + "Targetfleshycorpse:" + Targetfleshycorpse + ","
            + "Targetbonecorpse:" + Targetbonecorpse + ","
            + "Targetundead:" + Targetundead + ","
            + "Targetmechanical:" + Targetmechanical + ","
            + "Targetmoveable:" + Targetmoveable + ","
            + "Targetorganicground:" + Targetorganicground + ","
            + "Targetancient:" + Targetancient + ","
            + "Targetarmoredtransport:" + Targetarmoredtransport + ","
            + "Targetmanauser:" + Targetmanauser + ","
            + "Targetbunkerunit:" + Targetbunkerunit + ","
            + "Targetwisp:" + Targetwisp + ","
            + "Targetacolyte:" + Targetacolyte + ","
            + "Targetpit:" + Targetpit + ","
            + "Needemptytree:" + Needemptytree + ","
            + "Needowltree:" + Needowltree + ","
            + "Cantfindcorpse:" + Cantfindcorpse + ","
            + "Cantfindfriendlycorpse:" + Cantfindfriendlycorpse + ","
            + "Nounits:" + Nounits + ","
            + "Noground:" + Noground + ","
            + "Noair:" + Noair + ","
            + "Nostructure:" + Nostructure + ","
            + "Noward:" + Noward + ","
            + "Noitem:" + Noitem + ","
            + "Nodebris:" + Nodebris + ","
            + "Notree:" + Notree + ","
            + "Nowall:" + Nowall + ","
            + "Nobridge:" + Nobridge + ","
            + "Notfrozenbldg:" + Notfrozenbldg + ","
            + "Nonaval:" + Nonaval + ","
            + "Nottownhall:" + Nottownhall + ","
            + "Notownportalhalls:" + Notownportalhalls + ","
            + "Notself:" + Notself + ","
            + "Notowned:" + Notowned + ","
            + "Notfriendly:" + Notfriendly + ","
            + "Notneutral:" + Notneutral + ","
            + "Notenemy:" + Notenemy + ","
            + "Notcargo:" + Notcargo + ","
            + "Nothidden:" + Nothidden + ","
            + "Nothiddenitem:" + Nothiddenitem + ","
            + "Notinvulnerable:" + Notinvulnerable + ","
            + "Nohero:" + Nohero + ","
            + "Notcorpse:" + Notcorpse + ","
            + "Notfleshycorpse:" + Notfleshycorpse + ","
            + "Notbonecorpse:" + Notbonecorpse + ","
            + "Notmechanical:" + Notmechanical + ","
            + "Notorganic:" + Notorganic + ","
            + "Notdisabled:" + Notdisabled + ","
            + "Cantattackloc:" + Cantattackloc + ","
            + "Canttargetloc:" + Canttargetloc + ","
            + "Inventoryfull:" + Inventoryfull + ","
            + "Inventoryinteract:" + Inventoryinteract + ","
            + "NeedInventory:" + NeedInventory + ","
            + "Needretrainablehero:" + Needretrainablehero + ","
            + "Neednearbyhero:" + Neednearbyhero + ","
            + "Neednearbypatron:" + Neednearbypatron + ","
            + "Notsapper:" + Notsapper + ","
            + "Notancient:" + Notancient + ","
            + "Notsummoned:" + Notsummoned + ","
            + "Nottransport:" + Nottransport + ","
            + "Notunsummoned:" + Notunsummoned + ","
            + "Notillusion:" + Notillusion + ","
            + "Notmorphing:" + Notmorphing + ","
            + "Notdot:" + Notdot + ","
            + "Illusionscantharvest:" + Illusionscantharvest + ","
            + "Illusionscantpickup:" + Illusionscantpickup + ","
            + "Cantpolymorphunit:" + Cantpolymorphunit + ","
            + "Notundead:" + Notundead + ","
            + "Heromaxed:" + Heromaxed + ","
            + "HPmaxed:" + HPmaxed + ","
            + "Manamaxed:" + Manamaxed + ","
            + "HPmanamaxed:" + HPmanamaxed + ","
            + "UnitHPmaxed:" + UnitHPmaxed + ","
            + "UnitManaMaxed:" + UnitManaMaxed + ","
            + "RepairHPmaxed:" + RepairHPmaxed + ","
            + "Alreadybeinghealed:" + Alreadybeinghealed + ","
            + "Alreadybeingrepaired:" + Alreadybeingrepaired + ","
            + "Pitalreadysacrificing:" + Pitalreadysacrificing + ","
            + "Outofstock:" + Outofstock + ","
            + "Cooldownstock:" + Cooldownstock + ","
            + "Cantdrop:" + Cantdrop + ","
            + "Cantpawn:" + Cantpawn + ","
            + "Calltoarms:" + Calltoarms + ","
            + "Calltoarmspeasant:" + Calltoarmspeasant + ","
            + "Backtowork:" + Backtowork + ","
            + "Backtoworkmilitia:" + Backtoworkmilitia + ","
            + "BattleStations:" + BattleStations + ","
            + "Replaceme:" + Replaceme + ","
            + "Notliquidfirebldg:" + Notliquidfirebldg + ","
            + "Notethereal:" + Notethereal + ","
            + "Needstealbuff:" + Needstealbuff + ","
            + "Needmeleeattacker:" + Needmeleeattacker + ","
            + "Needrangedattacker:" + Needrangedattacker + ","
            + "Needspecialattacker:" + Needspecialattacker + ","
            + "Needattacker:" + Needattacker + ","
            + "Needcaster:" + Needcaster + ","
            + "Needattackerorcaster:" + Needattackerorcaster + ","
            + "Nopreservationtarget:" + Nopreservationtarget + ","
            + "Canttransformitem:" + Canttransformitem + ","
            + "Notmocunit:" + Notmocunit + ","
            + "Cantimpale:" + Cantimpale + ","
            + "Needpositivebuff:" + Needpositivebuff + ","
            + "Needposbufforsummoned:" + Needposbufforsummoned + ","
            + "Neednegativebuff:" + Neednegativebuff + ","
            + "Absorbmana:" + Absorbmana + ","
            + "Canttakeitem:" + Canttakeitem + ","
            + "Cantdropitem:" + Cantdropitem + ","
            + "Cantuseitem:" + Cantuseitem + ","
            + "Notpowerup:" + Notpowerup + ","
            + "Itemcooldown:" + Itemcooldown + ","
            + "Cantfindcoupletarget:" + Cantfindcoupletarget + ","
            + "Notdisabledinventory:" + Notdisabledinventory + ","
            + "Resistantskin:" + Resistantskin + ","
            + "Notinvulnerablespell:" + Notinvulnerablespell + ","
            + "Needsummoned:" + Needsummoned + ","
            + "Cantsubmergethere:" + Cantsubmergethere + ","
            + "Alreadydoomed:" + Alreadydoomed + ","
            + "}";
        }

        partial void EndRef();
    }

}

