
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ItemConfig : Luban.BeanBase
    {
        public ItemConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            TypeId = _buf.ReadString();
            Name = _buf.ReadString();
            Comment = _buf.ReadString();
            Description = _buf.ReadString();
            ItemClassType = _buf.ReadString();
            Level = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AbilList = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); AbilList[__index0] = __e0;}}
            ArmorType = _buf.ReadString();
            Tip = _buf.ReadString();
            Ubertip = _buf.ReadString();
            Hotkey = _buf.ReadString();
            Art = _buf.ReadString();
            File = _buf.ReadString();
            Scale = _buf.ReadFloat();
            SelSize = _buf.ReadFloat();
            GoldCost = _buf.ReadInt();
            LumberCost = _buf.ReadInt();
            MaxLife = _buf.ReadInt();
            StockStartDelay = _buf.ReadInt();
            StockReplenishInterval = _buf.ReadInt();
            StockMax = _buf.ReadInt();
            Priority = _buf.ReadInt();
            CooldownID = _buf.ReadString();
            IsIgnoreCooldown = _buf.ReadBool();
            IsValidTargetForTransformation = _buf.ReadBool();
            IsDroppedWhenCarrierDies = _buf.ReadBool();
            IsUseAutomaticallyWhenAcquired = _buf.ReadBool();
            IsSellable = _buf.ReadBool();
            IsPawnable = _buf.ReadBool();
            IsCanBeDropped = _buf.ReadBool();
            IsIncludeAsRandomChoice = _buf.ReadBool();
            NumberOfCharges = _buf.ReadInt();
            IsPerishable = _buf.ReadBool();
            IsActivelyUsed = _buf.ReadBool();

            EndInit();
        }

        public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
        {
            return new ItemConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 单位类型ID
        /// </summary>
        public readonly string TypeId;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 说明
        /// </summary>
        public readonly string Comment;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// 物品分类
        /// </summary>
        public readonly string ItemClassType;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
        /// <summary>
        /// 技能
        /// </summary>
        public readonly string[] AbilList;
        /// <summary>
        /// 装甲类型
        /// </summary>
        public readonly string ArmorType;
        /// <summary>
        /// 提示工具-基础
        /// </summary>
        public readonly string Tip;
        /// <summary>
        /// 提示工具-扩展
        /// </summary>
        public readonly string Ubertip;
        /// <summary>
        /// 热键
        /// </summary>
        public readonly string Hotkey;
        /// <summary>
        /// 图标
        /// </summary>
        public readonly string Art;
        /// <summary>
        /// 模型文件
        /// </summary>
        public readonly string File;
        /// <summary>
        /// 模型缩放
        /// </summary>
        public readonly float Scale;
        /// <summary>
        /// 选择圈大小(编辑器)
        /// </summary>
        public readonly float SelSize;
        /// <summary>
        /// 黄金消耗
        /// </summary>
        public readonly int GoldCost;
        /// <summary>
        /// 木材消耗
        /// </summary>
        public readonly int LumberCost;
        /// <summary>
        /// 生命最大值
        /// </summary>
        public readonly int MaxLife;
        /// <summary>
        /// 购买开始时间
        /// </summary>
        public readonly int StockStartDelay;
        /// <summary>
        /// 购买时间间隔
        /// </summary>
        public readonly int StockReplenishInterval;
        /// <summary>
        /// 最大库存量
        /// </summary>
        public readonly int StockMax;
        /// <summary>
        /// 优先权
        /// </summary>
        public readonly int Priority;
        /// <summary>
        /// CD间隔组
        /// </summary>
        public readonly string CooldownID;
        /// <summary>
        /// 无视CD间隔
        /// </summary>
        public readonly bool IsIgnoreCooldown;
        /// <summary>
        /// 有效的物品转换目标
        /// </summary>
        public readonly bool IsValidTargetForTransformation;
        /// <summary>
        /// 持有者死亡时掉落
        /// </summary>
        public readonly bool IsDroppedWhenCarrierDies;
        /// <summary>
        /// 拾取时自动使用
        /// </summary>
        public readonly bool IsUseAutomaticallyWhenAcquired;
        /// <summary>
        /// 可被市场出售
        /// </summary>
        public readonly bool IsSellable;
        /// <summary>
        /// 可以被抵押
        /// </summary>
        public readonly bool IsPawnable;
        /// <summary>
        /// 可以丢弃
        /// </summary>
        public readonly bool IsCanBeDropped;
        /// <summary>
        /// 可作为随机物品
        /// </summary>
        public readonly bool IsIncludeAsRandomChoice;
        /// <summary>
        /// 使用次数
        /// </summary>
        public readonly int NumberOfCharges;
        /// <summary>
        /// 使用完会消失
        /// </summary>
        public readonly bool IsPerishable;
        /// <summary>
        /// 主动使用
        /// </summary>
        public readonly bool IsActivelyUsed;
    
        public const int __ID__ = -764023723;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TypeId:" + TypeId + ","
            + "Name:" + Name + ","
            + "Comment:" + Comment + ","
            + "Description:" + Description + ","
            + "ItemClassType:" + ItemClassType + ","
            + "Level:" + Level + ","
            + "AbilList:" + Luban.StringUtil.CollectionToString(AbilList) + ","
            + "ArmorType:" + ArmorType + ","
            + "Tip:" + Tip + ","
            + "Ubertip:" + Ubertip + ","
            + "Hotkey:" + Hotkey + ","
            + "Art:" + Art + ","
            + "File:" + File + ","
            + "Scale:" + Scale + ","
            + "SelSize:" + SelSize + ","
            + "GoldCost:" + GoldCost + ","
            + "LumberCost:" + LumberCost + ","
            + "MaxLife:" + MaxLife + ","
            + "StockStartDelay:" + StockStartDelay + ","
            + "StockReplenishInterval:" + StockReplenishInterval + ","
            + "StockMax:" + StockMax + ","
            + "Priority:" + Priority + ","
            + "CooldownID:" + CooldownID + ","
            + "IsIgnoreCooldown:" + IsIgnoreCooldown + ","
            + "IsValidTargetForTransformation:" + IsValidTargetForTransformation + ","
            + "IsDroppedWhenCarrierDies:" + IsDroppedWhenCarrierDies + ","
            + "IsUseAutomaticallyWhenAcquired:" + IsUseAutomaticallyWhenAcquired + ","
            + "IsSellable:" + IsSellable + ","
            + "IsPawnable:" + IsPawnable + ","
            + "IsCanBeDropped:" + IsCanBeDropped + ","
            + "IsIncludeAsRandomChoice:" + IsIncludeAsRandomChoice + ","
            + "NumberOfCharges:" + NumberOfCharges + ","
            + "IsPerishable:" + IsPerishable + ","
            + "IsActivelyUsed:" + IsActivelyUsed + ","
            + "}";
        }

        partial void EndRef();
    }

}

