
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig : Luban.BeanBase
    {
        public UnitConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Type = _buf.ReadInt();
            Name = _buf.ReadString();
            Position = _buf.ReadInt();
            Weight = _buf.ReadInt();

            EndInit();
        }

        public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
        {
            return new UnitConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Type
        /// </summary>
        public readonly int Type;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 位置
        /// </summary>
        public readonly int Position;
        /// <summary>
        /// 体重
        /// </summary>
        public readonly int Weight;
    
        public const int __ID__ = -568528378;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "Name:" + Name + ","
            + "Position:" + Position + ","
            + "Weight:" + Weight + ","
            + "}";
        }

        partial void EndRef();
    }

}

