
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class War3ErrorsConfigCategory : Singleton<War3ErrorsConfigCategory>, ILubanConfig
    {

        private readonly War3ErrorsConfig _data;

        public War3ErrorsConfig Data => _data;

        public War3ErrorsConfigCategory(ByteBuf _buf)
        {
            int n = _buf.ReadSize();
            if (n != 1) throw new SerializationException("table mode=one, but size != 1");
            _data = global::ET.War3ErrorsConfig.DeserializeWar3ErrorsConfig(_buf);
			EndInit();
        }


        /// <summary>
        /// 不能组成空的控制编组。
        /// </summary>
        public string Emptycontrolgroup => _data.Emptycontrolgroup;
        /// <summary>
        /// 不能将非自己控制的单位编入控制编组中。
        /// </summary>
        public string Invalidcontrolgroup => _data.Invalidcontrolgroup;
        /// <summary>
        /// 编组只能由单位组成。
        /// </summary>
        public string Nonunitincontrolgroup => _data.Nonunitincontrolgroup;
        /// <summary>
        /// 建造更多的农场来继续生产单位。;建造更多的地洞来继续生产单位。;召唤更多的通灵塔来继续生产单位。;建造更多的月亮井来继续生产单位。
        /// </summary>
        public string Nofood => _data.Nofood;
        /// <summary>
        /// 达到食物上限，无法继续生产单位。
        /// </summary>
        public string Maxsupply => _data.Maxsupply;
        /// <summary>
        /// 黄金不足。
        /// </summary>
        public string Nogold => _data.Nogold;
        /// <summary>
        /// 木材不足。
        /// </summary>
        public string Nolumber => _data.Nolumber;
        /// <summary>
        /// 法力值不足。
        /// </summary>
        public string Nomana => _data.Nomana;
        /// <summary>
        /// 法术尚未就绪。
        /// </summary>
        public string Cooldown => _data.Cooldown;
        /// <summary>
        /// 运载空间不足。
        /// </summary>
        public string Noroom => _data.Noroom;
        /// <summary>
        /// 不能装载目标。
        /// </summary>
        public string Canttransport => _data.Canttransport;
        /// <summary>
        /// 不能吞噬该单位。
        /// </summary>
        public string Cantdevour => _data.Cantdevour;
        /// <summary>
        /// 不能对该单位施放飓风术。
        /// </summary>
        public string Cantcyclone => _data.Cantcyclone;
        /// <summary>
        /// 不能对该目标施放野性之魂。
        /// </summary>
        public string Cantspiritwolf => _data.Cantspiritwolf;
        /// <summary>
        /// 不能对该目标施放占据。
        /// </summary>
        public string Cantpossess => _data.Cantpossess;
        /// <summary>
        /// 不能对该目标施放法力燃烧。
        /// </summary>
        public string Cantmanaburn => _data.Cantmanaburn;
        /// <summary>
        /// 必须以战斗单位为目标。
        /// </summary>
        public string Onlyattackers => _data.Onlyattackers;
        /// <summary>
        /// 不能使用被缠绕的金矿。
        /// </summary>
        public string Notentangledmine => _data.Notentangledmine;
        /// <summary>
        /// 不能使用闹鬼金矿。
        /// </summary>
        public string Notblightedmine => _data.Notblightedmine;
        /// <summary>
        /// 该金矿已被缠绕。
        /// </summary>
        public string Alreadyentangled => _data.Alreadyentangled;
        /// <summary>
        /// 该金矿已变成闹鬼金矿。
        /// </summary>
        public string Alreadyblightedmine => _data.Alreadyblightedmine;
        /// <summary>
        /// 必须以树木或被缠绕的金矿为目标。
        /// </summary>
        public string Targetwispresources => _data.Targetwispresources;
        /// <summary>
        /// 必须以闹鬼金矿为目标。
        /// </summary>
        public string Targetblightedmine => _data.Targetblightedmine;
        /// <summary>
        /// 必须先将金矿缠绕。
        /// </summary>
        public string Entangleminefirst => _data.Entangleminefirst;
        /// <summary>
        /// 必须先让金矿变成闹鬼金矿。
        /// </summary>
        public string Blightminefirst => _data.Blightminefirst;
        /// <summary>
        /// 那个金矿不需要更多的小精灵。
        /// </summary>
        public string Entangledminefull => _data.Entangledminefull;
        /// <summary>
        /// 那个金矿不需要更多的侍僧。
        /// </summary>
        public string Blightringfull => _data.Blightringfull;
        /// <summary>
        /// 选中的侍僧已经在采矿了。
        /// </summary>
        public string Acolytealreadymining => _data.Acolytealreadymining;
        /// <summary>
        /// 不能使用被其他玩家控制的金矿。
        /// </summary>
        public string Nototherplayersmine => _data.Nototherplayersmine;
        /// <summary>
        /// 必须以金矿为目标。
        /// </summary>
        public string Targgetmine => _data.Targgetmine;
        /// <summary>
        /// 必须以资源为目标。
        /// </summary>
        public string Targgetresources => _data.Targgetresources;
        /// <summary>
        /// 必须以人类建筑为目标。
        /// </summary>
        public string Humanbuilding => _data.Humanbuilding;
        /// <summary>
        /// 必须以亡灵建筑为目标。
        /// </summary>
        public string Undeadbuilding => _data.Undeadbuilding;
        /// <summary>
        /// 该建筑正在建造中。
        /// </summary>
        public string Underconstruction => _data.Underconstruction;
        /// <summary>
        /// 该建筑已在建造中。
        /// </summary>
        public string Alreadyrebuilding => _data.Alreadyrebuilding;
        /// <summary>
        /// 这个生物太过强大。
        /// </summary>
        public string Creeptoopowerful => _data.Creeptoopowerful;
        /// <summary>
        /// 该单位已处于休眠状态。
        /// </summary>
        public string Hibernating => _data.Hibernating;
        /// <summary>
        /// 该单位已被束缚。
        /// </summary>
        public string Magicleashed => _data.Magicleashed;
        /// <summary>
        /// 该单位对魔法免疫。
        /// </summary>
        public string Immunetomagic => _data.Immunetomagic;
        /// <summary>
        /// 必须以友方生命单位或敌方亡灵单位为目标。
        /// </summary>
        public string Holybolttarget => _data.Holybolttarget;
        /// <summary>
        /// 必须以敌方生命单位或友方亡灵单位为目标。
        /// </summary>
        public string Deathcoiltarget => _data.Deathcoiltarget;
        /// <summary>
        /// 必须以一个单位或者一片荒芜为目标。
        /// </summary>
        public string Dispelmagictarget => _data.Dispelmagictarget;
        /// <summary>
        /// 这颗树已被占用，请选择其他树木。
        /// </summary>
        public string Treeoccupied => _data.Treeoccupied;
        /// <summary>
        /// 不能与该单位融合。
        /// </summary>
        public string Coupletarget => _data.Coupletarget;
        /// <summary>
        /// 必须以角鹰兽为目标。
        /// </summary>
        public string Mounthippogryphtarget => _data.Mounthippogryphtarget;
        /// <summary>
        /// 必须以弓箭手为目标。
        /// </summary>
        public string Archerridertarget => _data.Archerridertarget;
        /// <summary>
        /// 必须先探索那里。
        /// </summary>
        public string Cantsee => _data.Cantsee;
        /// <summary>
        /// 不能在那里建造。
        /// </summary>
        public string Cantplace => _data.Cantplace;
        /// <summary>
        /// 目标位置已超出地图边界。
        /// </summary>
        public string Outofbounds => _data.Outofbounds;
        /// <summary>
        /// 必须在荒芜之上召唤建筑。
        /// </summary>
        public string Offblight => _data.Offblight;
        /// <summary>
        /// 不能在离金矿太近的地方建造。
        /// </summary>
        public string Tooclosetomine => _data.Tooclosetomine;
        /// <summary>
        /// 不能在离城镇大厅太近的地方创建金矿。
        /// </summary>
        public string Tooclosetohall => _data.Tooclosetohall;
        /// <summary>
        /// 不能在远离海岸线的地方建造。
        /// </summary>
        public string Notonshoreline => _data.Notonshoreline;
        /// <summary>
        /// 没有空间可以放置新生产出的单位。
        /// </summary>
        public string Buildingblocked => _data.Buildingblocked;
        /// <summary>
        /// 该单位不能被传送。
        /// </summary>
        public string Teleportfail => _data.Teleportfail;
        /// <summary>
        /// 有东西封住了那根树桩。
        /// </summary>
        public string Stumpblocked => _data.Stumpblocked;
        /// <summary>
        /// 不能在那里着陆。
        /// </summary>
        public string Cantland => _data.Cantland;
        /// <summary>
        /// 不能在那里扎根。
        /// </summary>
        public string Cantroot => _data.Cantroot;
        /// <summary>
        /// 目标不能再扎根了。
        /// </summary>
        public string Cantrootunit => _data.Cantrootunit;
        /// <summary>
        /// 必须在金矿附近扎根以进行缠绕。
        /// </summary>
        public string Mustroottoentangle => _data.Mustroottoentangle;
        /// <summary>
        /// 必须在金矿附近扎根。
        /// </summary>
        public string Mustbeclosertomine => _data.Mustbeclosertomine;
        /// <summary>
        /// 该金矿不能被缠绕。
        /// </summary>
        public string Minenotentangleable => _data.Minenotentangleable;
        /// <summary>
        /// 目标超出射程。
        /// </summary>
        public string Notinrange => _data.Notinrange;
        /// <summary>
        /// 目标距离低于最小射程。
        /// </summary>
        public string UnderRange => _data.UnderRange;
        /// <summary>
        /// 不能以该单位为目标。
        /// </summary>
        public string Notthisunit => _data.Notthisunit;
        /// <summary>
        /// 该动作必须以单位为目标。
        /// </summary>
        public string Targetunit => _data.Targetunit;
        /// <summary>
        /// 必须以建筑或树木为目标。
        /// </summary>
        public string Targetstructuretree => _data.Targetstructuretree;
        /// <summary>
        /// 必须以地面单位为目标。
        /// </summary>
        public string Targetground => _data.Targetground;
        /// <summary>
        /// 必须以空中单位为目标。
        /// </summary>
        public string Targetair => _data.Targetair;
        /// <summary>
        /// 必须以建筑为目标。
        /// </summary>
        public string Targetstructure => _data.Targetstructure;
        /// <summary>
        /// 必须以结界为目标。
        /// </summary>
        public string Targetward => _data.Targetward;
        /// <summary>
        /// 必须以物品为目标。
        /// </summary>
        public string Targetitem => _data.Targetitem;
        /// <summary>
        /// 必须以树木为目标。
        /// </summary>
        public string Targettree => _data.Targettree;
        /// <summary>
        /// 必须以建筑和机械单位为目标。
        /// </summary>
        public string Targetrepair => _data.Targetrepair;
        /// <summary>
        /// 必须以桥梁为目标。
        /// </summary>
        public string Targetbridge => _data.Targetbridge;
        /// <summary>
        /// 必须以海上单位为目标。
        /// </summary>
        public string Targetnaval => _data.Targetnaval;
        /// <summary>
        /// 必须以你自己的单位为目标。
        /// </summary>
        public string Targetowned => _data.Targetowned;
        /// <summary>
        /// 必须以友方单位为目标。
        /// </summary>
        public string Targetally => _data.Targetally;
        /// <summary>
        /// 必须以中立单位为目标。
        /// </summary>
        public string Targetneutral => _data.Targetneutral;
        /// <summary>
        /// 必须以敌方单位为目标。
        /// </summary>
        public string Targetenemy => _data.Targetenemy;
        /// <summary>
        /// 必须以你能控制的单位为目标。
        /// </summary>
        public string Targetcontrol => _data.Targetcontrol;
        /// <summary>
        /// 必须以英雄为目标。
        /// </summary>
        public string Targethero => _data.Targethero;
        /// <summary>
        /// 必须以敌方英雄为目标。
        /// </summary>
        public string Targetenemyhero => _data.Targetenemyhero;
        /// <summary>
        /// 必须以尸体为目标。
        /// </summary>
        public string Targetcorpse => _data.Targetcorpse;
        /// <summary>
        /// 必须以血肉尸体为目标。
        /// </summary>
        public string Targetfleshycorpse => _data.Targetfleshycorpse;
        /// <summary>
        /// 必须以骨骼尸体为目标。
        /// </summary>
        public string Targetbonecorpse => _data.Targetbonecorpse;
        /// <summary>
        /// 必须以亡灵单位为目标。
        /// </summary>
        public string Targetundead => _data.Targetundead;
        /// <summary>
        /// 必须以机械单位为目标。
        /// </summary>
        public string Targetmechanical => _data.Targetmechanical;
        /// <summary>
        /// 必须以可移动单位为目标。
        /// </summary>
        public string Targetmoveable => _data.Targetmoveable;
        /// <summary>
        /// 必须以有机地面单位为目标。
        /// </summary>
        public string Targetorganicground => _data.Targetorganicground;
        /// <summary>
        /// 必须以古树为目标。
        /// </summary>
        public string Targetancient => _data.Targetancient;
        /// <summary>
        /// 必须以装甲载具为目标。
        /// </summary>
        public string Targetarmoredtransport => _data.Targetarmoredtransport;
        /// <summary>
        /// 必须以拥有法力值的单位为目标。
        /// </summary>
        public string Targetmanauser => _data.Targetmanauser;
        /// <summary>
        /// 必须以苦工为目标。
        /// </summary>
        public string Targetbunkerunit => _data.Targetbunkerunit;
        /// <summary>
        /// 必须以小精灵为目标。
        /// </summary>
        public string Targetwisp => _data.Targetwisp;
        /// <summary>
        /// 必须以侍僧为目标。
        /// </summary>
        public string Targetacolyte => _data.Targetacolyte;
        /// <summary>
        /// 必须以献祭深渊为目标。
        /// </summary>
        public string Targetpit => _data.Targetpit;
        /// <summary>
        /// 这颗树已经被一只猫头鹰占据。
        /// </summary>
        public string Needemptytree => _data.Needemptytree;
        /// <summary>
        /// 这颗树尚未被猫头鹰占据。
        /// </summary>
        public string Needowltree => _data.Needowltree;
        /// <summary>
        /// 附近没有可使用的尸体。
        /// </summary>
        public string Cantfindcorpse => _data.Cantfindcorpse;
        /// <summary>
        /// 附近没有友方单位的尸体。
        /// </summary>
        public string Cantfindfriendlycorpse => _data.Cantfindfriendlycorpse;
        /// <summary>
        /// 不能以单位为目标。
        /// </summary>
        public string Nounits => _data.Nounits;
        /// <summary>
        /// 不能以地面单位为目标。
        /// </summary>
        public string Noground => _data.Noground;
        /// <summary>
        /// 不能以空中单位为目标。
        /// </summary>
        public string Noair => _data.Noair;
        /// <summary>
        /// 不能以建筑为目标。
        /// </summary>
        public string Nostructure => _data.Nostructure;
        /// <summary>
        /// 不能以结界为目标。
        /// </summary>
        public string Noward => _data.Noward;
        /// <summary>
        /// 不能以物品为目标。
        /// </summary>
        public string Noitem => _data.Noitem;
        /// <summary>
        /// 不能以残骸为目标。
        /// </summary>
        public string Nodebris => _data.Nodebris;
        /// <summary>
        /// 不能以树木为目标。
        /// </summary>
        public string Notree => _data.Notree;
        /// <summary>
        /// 不能以墙壁为目标。
        /// </summary>
        public string Nowall => _data.Nowall;
        /// <summary>
        /// 不能以桥梁为目标。
        /// </summary>
        public string Nobridge => _data.Nobridge;
        /// <summary>
        /// 目标建筑已被冰冻。
        /// </summary>
        public string Notfrozenbldg => _data.Notfrozenbldg;
        /// <summary>
        /// 不能以海上单位为目标。
        /// </summary>
        public string Nonaval => _data.Nonaval;
        /// <summary>
        /// 必须以友方城镇大厅为目标。;必须以友方大厅为目标。;必须以友方城镇大厅为目标。;必须以友方城镇大厅为目标。
        /// </summary>
        public string Nottownhall => _data.Nottownhall;
        /// <summary>
        /// 没有友方城镇大厅可作为城镇传送的目标。;没有友方大厅可作为城镇传送的目标。;没有友方城镇大厅可作为城镇传送的目标。;没有友方城镇大厅可作为城镇传送的目标。
        /// </summary>
        public string Notownportalhalls => _data.Notownportalhalls;
        /// <summary>
        /// 不能以自身为目标。
        /// </summary>
        public string Notself => _data.Notself;
        /// <summary>
        /// 不能以自己的单位为目标。
        /// </summary>
        public string Notowned => _data.Notowned;
        /// <summary>
        /// 不能以友方单位为目标。
        /// </summary>
        public string Notfriendly => _data.Notfriendly;
        /// <summary>
        /// 不能以中立单位为目标。
        /// </summary>
        public string Notneutral => _data.Notneutral;
        /// <summary>
        /// 不能以敌方单位为目标。
        /// </summary>
        public string Notenemy => _data.Notenemy;
        /// <summary>
        /// 无法以建筑或载具内的单位为目标。
        /// </summary>
        public string Notcargo => _data.Notcargo;
        /// <summary>
        /// 目标在地图上不可见。
        /// </summary>
        public string Nothidden => _data.Nothidden;
        /// <summary>
        /// 不能以携带的物品为目标。
        /// </summary>
        public string Nothiddenitem => _data.Nothiddenitem;
        /// <summary>
        /// 目标是无敌的。
        /// </summary>
        public string Notinvulnerable => _data.Notinvulnerable;
        /// <summary>
        /// 不能以英雄为目标。
        /// </summary>
        public string Nohero => _data.Nohero;
        /// <summary>
        /// 目标必须是生命单位。
        /// </summary>
        public string Notcorpse => _data.Notcorpse;
        /// <summary>
        /// 不能以血肉尸体为目标。
        /// </summary>
        public string Notfleshycorpse => _data.Notfleshycorpse;
        /// <summary>
        /// 不能以骨骼尸体为目标。
        /// </summary>
        public string Notbonecorpse => _data.Notbonecorpse;
        /// <summary>
        /// 必须以有机单位为目标。
        /// </summary>
        public string Notmechanical => _data.Notmechanical;
        /// <summary>
        /// 不能以有机单位为目标。
        /// </summary>
        public string Notorganic => _data.Notorganic;
        /// <summary>
        /// 施法单位移动已被禁用。
        /// </summary>
        public string Notdisabled => _data.Notdisabled;
        /// <summary>
        /// 不能进攻那里。
        /// </summary>
        public string Cantattackloc => _data.Cantattackloc;
        /// <summary>
        /// 不能以那里为目标。
        /// </summary>
        public string Canttargetloc => _data.Canttargetloc;
        /// <summary>
        /// 物品栏已满。
        /// </summary>
        public string Inventoryfull => _data.Inventoryfull;
        /// <summary>
        /// 选择一个拥有物品栏的单位。
        /// </summary>
        public string Inventoryinteract => _data.Inventoryinteract;
        /// <summary>
        /// 只有带有物品栏的单位才能捡起该物品。
        /// </summary>
        public string NeedInventory => _data.NeedInventory;
        /// <summary>
        /// 只有技能冷却完毕的英雄才能使用该物品。
        /// </summary>
        public string Needretrainablehero => _data.Needretrainablehero;
        /// <summary>
        /// 周围必须有一个英雄。
        /// </summary>
        public string Neednearbyhero => _data.Neednearbyhero;
        /// <summary>
        /// 周围必须有一个有效的支持目标。
        /// </summary>
        public string Neednearbypatron => _data.Neednearbypatron;
        /// <summary>
        /// 不能以工兵为目标。
        /// </summary>
        public string Notsapper => _data.Notsapper;
        /// <summary>
        /// 不能以古树为目标。
        /// </summary>
        public string Notancient => _data.Notancient;
        /// <summary>
        /// 不能以召唤单位为目标。
        /// </summary>
        public string Notsummoned => _data.Notsummoned;
        /// <summary>
        /// 不能以载具和掩体为目标。
        /// </summary>
        public string Nottransport => _data.Nottransport;
        /// <summary>
        /// 该单位正在被反召唤。
        /// </summary>
        public string Notunsummoned => _data.Notunsummoned;
        /// <summary>
        /// 不能以幻象为目标。
        /// </summary>
        public string Notillusion => _data.Notillusion;
        /// <summary>
        /// 不能以变形单位为目标。
        /// </summary>
        public string Notmorphing => _data.Notmorphing;
        /// <summary>
        /// 不能以猛禽德鲁伊为目标。
        /// </summary>
        public string Notdot => _data.Notdot;
        /// <summary>
        /// 幻象不能采集资源。
        /// </summary>
        public string Illusionscantharvest => _data.Illusionscantharvest;
        /// <summary>
        /// 幻象不能捡起物品。
        /// </summary>
        public string Illusionscantpickup => _data.Illusionscantpickup;
        /// <summary>
        /// 该单位对变形术免疫。
        /// </summary>
        public string Cantpolymorphunit => _data.Cantpolymorphunit;
        /// <summary>
        /// 不能以亡灵单位为目标。
        /// </summary>
        public string Notundead => _data.Notundead;
        /// <summary>
        /// 英雄已达到最高等级。
        /// </summary>
        public string Heromaxed => _data.Heromaxed;
        /// <summary>
        /// 英雄的生命值已满。
        /// </summary>
        public string HPmaxed => _data.HPmaxed;
        /// <summary>
        /// 法力值已满。
        /// </summary>
        public string Manamaxed => _data.Manamaxed;
        /// <summary>
        /// 生命值和法力值已满。
        /// </summary>
        public string HPmanamaxed => _data.HPmanamaxed;
        /// <summary>
        /// 生命值已满。
        /// </summary>
        public string UnitHPmaxed => _data.UnitHPmaxed;
        /// <summary>
        /// 法力值已满。
        /// </summary>
        public string UnitManaMaxed => _data.UnitManaMaxed;
        /// <summary>
        /// 目标并未受到伤害。
        /// </summary>
        public string RepairHPmaxed => _data.RepairHPmaxed;
        /// <summary>
        /// 目标已受到治疗。
        /// </summary>
        public string Alreadybeinghealed => _data.Alreadybeinghealed;
        /// <summary>
        /// 目标已受到修理。
        /// </summary>
        public string Alreadybeingrepaired => _data.Alreadybeingrepaired;
        /// <summary>
        /// 献祭深渊已在献祭一名侍僧。
        /// </summary>
        public string Pitalreadysacrificing => _data.Pitalreadysacrificing;
        /// <summary>
        /// 已断货
        /// </summary>
        public string Outofstock => _data.Outofstock;
        /// <summary>
        /// 已断货
        /// </summary>
        public string Cooldownstock => _data.Cooldownstock;
        /// <summary>
        /// 物品必须放在物品栏中。
        /// </summary>
        public string Cantdrop => _data.Cantdrop;
        /// <summary>
        /// 物品不能被抵押掉。
        /// </summary>
        public string Cantpawn => _data.Cantpawn;
        /// <summary>
        /// 找不到任何农夫。
        /// </summary>
        public string Calltoarms => _data.Calltoarms;
        /// <summary>
        /// 没有找到可以将民兵转换成农夫的城镇大厅。
        /// </summary>
        public string Calltoarmspeasant => _data.Calltoarmspeasant;
        /// <summary>
        /// 找不到任何民兵。
        /// </summary>
        public string Backtowork => _data.Backtowork;
        /// <summary>
        /// 没有找到可以将民兵转换成农夫的城镇大厅。
        /// </summary>
        public string Backtoworkmilitia => _data.Backtoworkmilitia;
        /// <summary>
        /// 找不到任何苦工。
        /// </summary>
        public string BattleStations => _data.BattleStations;
        /// <summary>
        /// 请用有意义的文字来替换这条错误消息！
        /// </summary>
        public string Replaceme => _data.Replaceme;
        /// <summary>
        /// 目标建筑已被火油瓶点燃。
        /// </summary>
        public string Notliquidfirebldg => _data.Notliquidfirebldg;
        /// <summary>
        /// 虚灵单位只会受到法术和魔法攻击的伤害。
        /// </summary>
        public string Notethereal => _data.Notethereal;
        /// <summary>
        /// 目标身上没有可窃取的魔法效果。
        /// </summary>
        public string Needstealbuff => _data.Needstealbuff;
        /// <summary>
        /// 必须以近战单位为目标。
        /// </summary>
        public string Needmeleeattacker => _data.Needmeleeattacker;
        /// <summary>
        /// 必须以远程战斗单位为目标。
        /// </summary>
        public string Needrangedattacker => _data.Needrangedattacker;
        /// <summary>
        /// 必须以特定战斗单位为目标。
        /// </summary>
        public string Needspecialattacker => _data.Needspecialattacker;
        /// <summary>
        /// 必须以战斗单位为目标。
        /// </summary>
        public string Needattacker => _data.Needattacker;
        /// <summary>
        /// 必须以施法单位为目标。
        /// </summary>
        public string Needcaster => _data.Needcaster;
        /// <summary>
        /// 必须以战斗单位或施法单位为目标。
        /// </summary>
        public string Needattackerorcaster => _data.Needattackerorcaster;
        /// <summary>
        /// 没有可将目标传送过去的建筑。
        /// </summary>
        public string Nopreservationtarget => _data.Nopreservationtarget;
        /// <summary>
        /// 不能转换该物品。
        /// </summary>
        public string Canttransformitem => _data.Canttransformitem;
        /// <summary>
        /// 该单位已被火焰标记。
        /// </summary>
        public string Notmocunit => _data.Notmocunit;
        /// <summary>
        /// 不能刺穿该单位。
        /// </summary>
        public string Cantimpale => _data.Cantimpale;
        /// <summary>
        /// 必须以带有增益效果的敌方单位为目标。
        /// </summary>
        public string Needpositivebuff => _data.Needpositivebuff;
        /// <summary>
        /// 必须以带有增益效果的敌方单位或召唤单位为目标。
        /// </summary>
        public string Needposbufforsummoned => _data.Needposbufforsummoned;
        /// <summary>
        /// 必须以带有减益效果的友方单位为目标。
        /// </summary>
        public string Neednegativebuff => _data.Neednegativebuff;
        /// <summary>
        /// 法力不足，无法吸收。
        /// </summary>
        public string Absorbmana => _data.Absorbmana;
        /// <summary>
        /// 不能捡起该物品。
        /// </summary>
        public string Canttakeitem => _data.Canttakeitem;
        /// <summary>
        /// 不能丢掉该物品。
        /// </summary>
        public string Cantdropitem => _data.Cantdropitem;
        /// <summary>
        /// 不能使用该物品。
        /// </summary>
        public string Cantuseitem => _data.Cantuseitem;
        /// <summary>
        /// 不能使用道具。
        /// </summary>
        public string Notpowerup => _data.Notpowerup;
        /// <summary>
        /// 该物品正在冷却。
        /// </summary>
        public string Itemcooldown => _data.Itemcooldown;
        /// <summary>
        /// 不能找到配对目标。
        /// </summary>
        public string Cantfindcoupletarget => _data.Cantfindcoupletarget;
        /// <summary>
        /// 该单位的物品栏已被禁用。
        /// </summary>
        public string Notdisabledinventory => _data.Notdisabledinventory;
        /// <summary>
        /// 该单位拥有抗性体肤。
        /// </summary>
        public string Resistantskin => _data.Resistantskin;
        /// <summary>
        /// 不能使用给予无敌的法术和物品。
        /// </summary>
        public string Notinvulnerablespell => _data.Notinvulnerablespell;
        /// <summary>
        /// 必须以召唤单位为目标。
        /// </summary>
        public string Needsummoned => _data.Needsummoned;
        /// <summary>
        /// 不能在那里潜水。
        /// </summary>
        public string Cantsubmergethere => _data.Cantsubmergethere;
        /// <summary>
        /// 该单位已受到末日降临的折磨。
        /// </summary>
        public string Alreadydoomed => _data.Alreadydoomed;
        
        public void ResolveRef()
        {
            _data.ResolveRef();
            EndRef();
        }

        partial void EndRef();
    }

}

